// Generated by typings
// Source: https://raw.githubusercontent.com/cowbell/cordova-plugin-geofence/master/typings/cordova-plugin-geofence.d.ts
interface TransitionType {
  ENTER: number;
  EXIT: number;
  BOTH: number;
}

interface Window {
  geofence: RunningDrillsPlugin;
  TransitionType: TransitionType;
}

interface RunningDrillsPlugin {
  initialize(
    successCallback?: (result: any) => void,
    errorCallback?: (error: string) => void
  ): Promise<any>;

  addOrUpdate(
    geofence: TrainingSession | TrainingSession[],
    successCallback?: (result: any) => void,
    errorCallback?: (error: string) => void
  ): Promise<any>;

  remove(
    id: number | number[],
    successCallback?: (result: any) => void,
    errorCallback?: (error: string) => void
  ): Promise<any>;

  removeAll(
    successCallback?: (result: any) => void,
    errorCallback?: (error: string) => void
  ): Promise<any>;

  getWatched(
    successCallback?: (result: any) => void,
    errorCallback?: (error: string) => void
  ): Promise<string>;

  onTransitionReceived: (trainingSession: TrainingSession[]) => void;
}


interface TrainingSession {
  id: string;
  description: string;
  userGroupName: string;
  show: boolean;  
  intervals: string;
  drills: Drill[];
  groups: Group[];
}

interface Group {
  groupName: string;
  drills: Drill[];
}

interface Drill {
  id: string;
  drillIdx: number;
  title: string;
  description: string;
  imgUrl: string;
  locations: string;
  tags: string;
  orderBy: number;
  videoUrl: string;
}

interface RunningGroup {
  name: string;
  title: string;
  value: boolean;
}



/*
$drills[4] = array(  
  id => 4,
  title => 'Tripplings met kniehef(vasthouden)',
  description => "Tripplings op de plaats met kniehef, kniehef paar sec. vasthouden.",
  tags => array( "warming up", "loopscholing" ),
  locations => array( "circle"),
  musclegroups=> array( ) ) ;


$trainings['20160914']['description'] = "Veel kort werk vanavond. Extra aandacht voor core stability";
$trainings['20160914']['date'] = "2016-09-14";
$trainings['20160914']['drillMappings'][]["warming up"] = array (1);
$trainings['20160914']['drillMappings'][]["circle"] = array (2, 3);
*/